spring:
  application:
    name: gateway-api
    
server:
  port: 7500
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka/

zuul:
  routes:
    service-customer: 
      path: /api-customer/**
      service-id: service-customer
    
