spring:
  application:
    name: service-housing
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lovehouse
    username: root
    password: 12234
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      max-active: 20
    
server:
  port: 8200
  session:
    timeout: 10
  tomcat:
    uri-encoding: UTF-8
    
mybatis:
  mapper-locations:
  - classpath:mappers/*.xml      
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka/  


