spring:
  application:
    name: service-customer
    
server:
  port: 8300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka/ 


#feign:
#  hystrix:
#    enabled: true

